package com.lzq.springbootredis.dao;

import com.lzq.springbootredis.model.UserMessage;
import org.springframework.stereotype.Component;

import java.util.List;
@Component("UserMessageMapper")
public interface UserMessageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    int insert(UserMessage record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    List<UserMessage> selectByExample();


}